version: "3.9"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    privileged: true
    shm_size: 2g
  app:
    build: .
    depends_on:
      - "chrome"
    command: ["./sub_sale_bot/wait-for-it.sh", "chrome:4444", "--", "python", "./sub_sale_bot.py"]