version: "3.8"

services:
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    ports:
      - '4444:4444'
      - '5900:5900'
    networks:
      - default
    privileged: true
    shm_size: 2g
  app:
    build: .
    networks:
      - default
    depends_on:
      - chrome